### ISSUE TITLE
Root phpcs.xml missing

### ISSUE THREAD

**Issue by dereuromark** [spryker-sdk/upgrader#62]
https://github.com/spryker-sdk/upgrader/blob/master/composer.json#L65-L66

Please make sure to use new standard and root phpcs.xml like other repos
https://github.com/spryker-sdk/sdk/blob/master/composer.json#L104-L105 etc

**Comment by DmytroKlymanSpryker** [comment]
PR: https://github.com/spryker-sdk/upgrader/pull/65/files
